"""The storage contract both backends implement.

The service layer depends on this Protocol, not a concrete store, so the same
rules run over **SQLite** (deterministic tests, local dev) or **PostgreSQL**
(durable production state) with no change above this line. Every method speaks in
plain dicts; the service maps those to the shared `packages.schemas` payloads.
"""
from __future__ import annotations

from typing import Protocol


class StoreProtocol(Protocol):
    # --- channels & membership ---
    def create_channel(
        self, channel_type: str, name: str | None, correlation_id: str | None,
        creator: str, members: list[str],
    ) -> dict: ...
    def get_channel(self, channel_id: str) -> dict | None: ...
    def add_member(self, channel_id: str, agent_id: str, role: str = "member") -> None: ...
    def is_member(self, channel_id: str, agent_id: str) -> bool: ...
    def member_role(self, channel_id: str, agent_id: str) -> str | None: ...
    def members(self, channel_id: str) -> list[str]: ...
    def channels_for(self, agent_id: str) -> list[dict]: ...
    # --- messages (append-only) ---
    def add_message(
        self, channel_id: str, sender_id: str, body: str, source: str,
        trust_label: str, mentions: list[str], correlation_id: str | None,
    ) -> dict: ...
    def get_message(self, message_id: str) -> dict | None: ...
    def messages_since(self, channel_id: str, since: int = 0) -> list[dict]: ...
    def all_messages_since(self, since: int = 0) -> list[dict]: ...
